apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mariadb.cred_name }}
type: Opaque
data:
  dbname: {{ .Values.mariadb.cred.dbname }}
  dbpassword: {{ .Values.mariadb.cred.dbpassword }}
  dbrootpassword: {{ .Values.mariadb.cred.dbrootpassword }}
  dbuser: {{ .Values.mariadb.cred.dbuser }}

