apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mediawiki.service.name }}
spec:
  type: {{ .Values.mediawiki.service.type }}
  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
      {{- if eq .Values.mediawiki.service.type "NodePort" }}
    - nodePort:  {{ .Values.mediawiki.service.port }}
      {{- end }}
      port:  {{ .Values.mediawiki.service.pod_port }}
      targetPort:  {{ .Values.mediawiki.service.target_port }}
  selector:
    app: {{ .Values.mediawiki.deployment.name }}