name: deploy_mediawiki_k8s

on:
  push:
    paths:
    - 'mediawiki_chart/**'
    - '.github/workflows/**'
  pull_request:
    paths:
    - 'mediawiki_chart/**'
    - '.github/workflows/**'
      
jobs:
  deployment:
    name: Start K8s cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate Minikube
        run: minikube status | grep Running

      - name: Validate Cluster
        run: kubectl get nodes

      - name: Get Minikube status
        run: minikube status

      - name: Get cluster info
        run: kubectl cluster-info

      - name: Get Kubernetes pods
        run: kubectl get services --all-namespaces

      - name: Get Minikube IP
        run: echo ${{ steps.minikube.outputs.ip }}

      - name: Get Docker containers
        run: docker ps

      - name: Install helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
          sudo apt-get install apt-transport-https --yes
          echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm    
      
      - name: Get helm version
        run: |
          helm version
          helm list
        
      - name: Lint helm-chart
        run: helm lint ./mediawiki_chart
      
      - name: Perform dry-run
        run: |
          echo -n ${{ secrets.DBNAME }} | base64
          echo -n ${{ secrets.DBPASSWORD }} | base64
          echo -n ${{ secrets.DBROOTPASSWORD }} | base64
          echo -n ${{ secrets.DBUSER }} | base64
          helm install --dry-run --debug mediawiki ./mediawiki_chart
      
      - name: Install mediawiki
        run: helm install mediawiki ./mediawiki_chart
        
        
